/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Checkbox: typeof import('./src/components/checkbox/index.vue')['default']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    Pagination: typeof import('./src/components/pagination/index.vue')['default']
    Phopopover: typeof import('./src/components/phopopover/index.vue')['default']
    Radio: typeof import('./src/components/radio/index.vue')['default']
    Right: typeof import('./src/components/right/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/table/index.vue')['default']
  }
}
